# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chat App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chat App
    pod 'FirebaseCore'
    pod 'FirebaseDatabase'
    pod 'FirebaseAuth'
    pod 'AppAuth','~> 1.2.0'

end
